/*
Author: Arafat Hossain Ar
Date: 09/12/2020
Project Name: Lina The Talking Bot
Version: 1.1
 */

package linathebot;

import linaVoiceUI.LinaVoice;
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.awt.AWTException;
import java.awt.Robot;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import voice.recognizer.voiceRecognizer;

/**
 *
 * @author Arafat Hossain Ar
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    //Voice objects
    VoiceManager voicemanager;
    Voice voice;
   
    private static final String voicename = "kevin16";
    

    //Mouse position
    int xMouse;
    int yMouse;

    public MainFrame() {
        initComponents();
        
        //Mbrola voice properties
        System.setProperty("mbrola.base", "src/mbrola");
        voicemanager = VoiceManager.getInstance();

        // Simply change to MBROLA voice
        voice = voicemanager.getVoice("mbrola_us1");

        // Allocate your chosen voice
        voice.allocate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        greetingText = new javax.swing.JLabel();
        linaLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        infoBtn = new javax.swing.JLabel();
        voiceStart = new javax.swing.JLabel();
        settingsBtn = new javax.swing.JLabel();
        quitBtnVoicePanel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        topBar = new javax.swing.JPanel();
        quitBtn = new javax.swing.JLabel();
        helpBtn = new javax.swing.JLabel();
        inputBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lina The Bot");
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setForeground(new java.awt.Color(0, 0, 0));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greetingText.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        greetingText.setForeground(new java.awt.Color(0, 0, 0));
        greetingText.setText("Hi There! I'm Lina");
        mainPanel.add(greetingText, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        linaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/linathebot/logs/logo.png"))); // NOI18N
        mainPanel.add(linaLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Voice Control Panel");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(180, 180, 180))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        infoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/linathebot/logs/info.png"))); // NOI18N

        voiceStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/linathebot/logs/microphone.png"))); // NOI18N
        voiceStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voiceStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voiceStartMouseClicked(evt);
            }
        });

        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/linathebot/logs/settings.png"))); // NOI18N

        quitBtnVoicePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/linathebot/logs/quit.png"))); // NOI18N
        quitBtnVoicePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitBtnVoicePanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(infoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(voiceStart)
                .addGap(71, 71, 71)
                .addComponent(settingsBtn)
                .addGap(59, 59, 59)
                .addComponent(quitBtnVoicePanel)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoBtn)
                    .addComponent(voiceStart)
                    .addComponent(settingsBtn)
                    .addComponent(quitBtnVoicePanel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, 110));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 318, -1, -1));

        topBar.setBackground(new java.awt.Color(204, 204, 204));
        topBar.setForeground(new java.awt.Color(0, 0, 0));
        topBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topBarMouseDragged(evt);
            }
        });
        topBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topBarMousePressed(evt);
            }
        });

        quitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/linathebot/logs/exit.png"))); // NOI18N
        quitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitBtnMouseClicked(evt);
            }
        });

        helpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/linathebot/logs/help.png"))); // NOI18N

        javax.swing.GroupLayout topBarLayout = new javax.swing.GroupLayout(topBar);
        topBar.setLayout(topBarLayout);
        topBarLayout.setHorizontalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quitBtn)
                .addContainerGap())
        );
        topBarLayout.setVerticalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
            .addComponent(helpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPanel.add(topBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 749, -1));

        inputBox.setBackground(new java.awt.Color(204, 204, 204));
        inputBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        inputBox.setForeground(new java.awt.Color(0, 0, 0));
        inputBox.setToolTipText("your command");
        inputBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBoxActionPerformed(evt);
            }
        });
        mainPanel.add(inputBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 310, 44));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(749, 583));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBoxActionPerformed
        // TODO add your handling code here:
        
        //Get text from inputbox
        String getText = inputBox.getText().toLowerCase();
        
        //set text as null after taking input
        inputBox.setText("");
        
        //Greeting msges
        try {
            if (getText.contains("hi") || getText.contains("hello") || getText.contains("hola")) {
                final int MAXNUM = 2;
                double getRandomNumber = Math.random();
                int randomNumber = (int) (getRandomNumber * MAXNUM);
                switch (randomNumber) {
                    case 0:
                        voice.speak("Hello Sir!");
                        break;
                    case 1:
                        voice.speak("Hay Sir!");
                        break;
                    case 2:
                        voice.speak("Hola!");
                        break;
                    default:
                        break;
                }
                //voice.speak("Hello");
            } else if (getText.contains("name")) {
                voice.speak("My name is Lina");
            } else if (getText.contains("help")) {
                voice.speak("Yes! I can help you.");
            } else if (getText.contains("how are you")) {
                voice.speak("I am fine");
            } else if (getText.contains("facebook")) {
                voice.speak(" Facebook is a website for the Worldwide Social Interaction System, which was established on February 7, 2015. It can be a free member. It is owned by Facebook Inc.");
            } else if (getText.contains("notepad")) {
                voice.speak("Opening notepad");
                Robot robot = null;
                try {
                    robot = new Robot();
                } catch (AWTException ex) {
                }
                robot.delay(1000);
                Runtime run = Runtime.getRuntime();
                try {
                    run.exec("notepad.exe");
                } catch (IOException ex) {
                }

            } else if (getText.contains("chrome")) {
                voice.speak("Opening chrome browser");
                Robot robot = null;
                try {
                    robot = new Robot();
                } catch (AWTException ex) {
                }
                robot.delay(1000);

                try {
                    String command = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe";
                    Runtime run = Runtime.getRuntime();
                    run.exec(command);
                } catch (IOException ex) {
                }

            } else if (getText.contains("thank")) {
                voice.speak("Welcome Sir!");
            } else {
                final int MAXNUM = 3;
                double getRandomNumber = Math.random();
                int randomNumber = (int) (getRandomNumber * MAXNUM);
                switch (randomNumber) {
                    case 0:
                        voice.speak("I Don't Understand");
                        break;
                    case 1:
                        voice.speak("Sorry, I Don't Understand");
                        break;
                    case 2:
                        voice.speak("I'm Not Programmed to Response that");
                        break;
                    case 3:
                        voice.speak("Come Again Please");
                        break;
                    default:
                        break;
                }
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_inputBoxActionPerformed

    private void topBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarMousePressed
        // TODO add your handling code here:
        
        //mouse movement
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_topBarMousePressed

    private void topBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarMouseDragged
        // TODO add your handling code here:
        
        //mouse movement control
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_topBarMouseDragged

    private void quitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitBtnMouseClicked

    private void voiceStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voiceStartMouseClicked

        this.dispose();
        thread1.start();
        thread2.start();

    }//GEN-LAST:event_voiceStartMouseClicked

    private void quitBtnVoicePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitBtnVoicePanelMouseClicked
        // TODO add your handling code here:
        // voiceRecognizer vr =   new voiceRecognizer().;
    }//GEN-LAST:event_quitBtnVoicePanelMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//  //      UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel greetingText;
    private javax.swing.JLabel helpBtn;
    private javax.swing.JLabel infoBtn;
    private javax.swing.JTextField inputBox;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel linaLogo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel quitBtn;
    private javax.swing.JLabel quitBtnVoicePanel;
    private javax.swing.JLabel settingsBtn;
    private javax.swing.JPanel topBar;
    private javax.swing.JLabel voiceStart;
    // End of variables declaration//GEN-END:variables

    Thread thread1 = new Thread() {
        public void run() {
            new LinaVoice().setVisible(true);
        }
    };

    //Thread to run to different window
    Thread thread2 = new Thread() {
        public void run() {
            voiceRecognizer vr = new voiceRecognizer();
            try {
                vr.voiceDetect();
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (URISyntaxException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (AWTException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    };

}
